apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    argocd/app-selector: rhdh.redhat.com/app-name=${{ values.name }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://${{ values.gitlab_host }}/${{ values.gitlab_group }}/${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.name }}-dev
    backstage.io/kubernetes-id: ${{ values.name }}
    janus-idp.io/tekton: ${{ values.name }}-build
    gitlab.com/project-slug: ${{ values.gitlab_group }}/${{ values.name }}
    jira/project-key: ${{ values.name | upper }}
    quay.io/repository-slug: parasol/${{ values.name }}
  links:
    - url: https://devspaces.${{ values.cluster_subdomain }}/#https://${{ values.gitlab_host }}/${{ values.gitlab_group }}/${{ values.name }}
      title: Open in Dev Spaces
      icon: catalog
      type: devspaces
spec:
  type: service
  lifecycle: development
  owner: ${{ values.owner }}
